### ISSUE TITLE
Feedback R

### ISSUE THREAD

**Issue by Joni32do** [Simtequilas2019/MWT#1]
Ich habe gerade mal etwas euren Code überflogen und wollte mal nach eurem Feedback fragen, welche Besonderheiten und Möglichkeiten R bietet? Die Syntax erscheint erstmal etwas gewöhnungsbedürftig, aber so wie es aussieht sind viele Funktionalitäten bereits eingebaut. Hilft das bei entsprechender IDE im Kontrast zu Libraries?

_Liebe GitHub Grüße_
Joni

**Comment by ullmannsven** [comment]
Aktuell sehen wir kaum Vorteile (alles könnte man auch genau so simpel in Matlab oder python machen, grad in matlab braucht man ja keine Libraries importieren). R ist wohl the way to go in der Statistik und stochastischen Modellierung, kann glaub gut mit großen Datenmengen umgehen, wobei das ja für die Programmiertasks auf der Blättern eher irrelevant ist
